spring.application.name=quizapp
spring.datasource.url=jdbc:postgresql://localhost:5432/quiz_db
spring.datasource.username=postgres
spring.datasource.password=Cyclotron@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
